name: TamodaWortiseAds
description: Ekstensi Wortise Ads (App Open, Banner, Interstitial, Rewarded)
version: '1'
author: Goes Pro

# TAMBAHKAN INI: Alamat gudang SDK
repositories:
  - google()
  - mavenCentral()
  - url: https://maven.wortise.com/artifactory/public

dependencies:
  - com.wortise:android-sdk:1.6.0
  - com.google.android.gms:play-services-ads-identifier:18.0.1

build:
  release:
    optimize: true

java:
  source: '1.8'
  target: '1.8'

manifest:
  application:
    attributes:
      android:hardwareAccelerated: "true"
      android:usesCleartextTraffic: "true"
